### PR TITLE
fix error and verbose logging for windows services

### PR DESCRIPTION
**Pull request by ghost**
or any process that doesn't have stdout/stderr.

by default, stderr is added to the error writes. and in case of
verbose, stdout is added.  added to an io.MultiWriter.  however,
the multiwriter stops writing on first error.  processes (such as
windows services, at least those created using github.com/judwhite/go-svc)
don't have stdout/stderr, and writes will fail.  and that logging
will never end up in the windows event logger.

an better fix would be to not use io.MultiWriter, but create a new
multiwriter that continues on failures.

### CODE REVIEW

**Comment by irias** [comment]
i signed the cla... both on my company email address (which is not in the commit), and personally (which is in the commit).

**Comment by pkern** [comment]
This is due to the mismatch of the author of the pull request (irias) and the commit author (mjl-). Can you comment from the other account here as well that you're ok with it? Sorry about that. (Also cla/google won't pick it up as this is a terminal state at this point. CLAs are signed means that the groundwork is done, though.)

**Comment by mjl-** [comment]
hi, me from other account here. this account signed the cla too. all is ok. let me know if i need to do anything else.

**Review by adjackura — APPROVED** [review]

**Comment by adjackura** [comment]
Double checked and CLA's are signed.

**Pull request merged**
